apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuevue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuevue
  template:
    metadata:
      labels:
        app: vuevue
    spec:
      containers:
      - image: tiramisubliss/vuevue:2.0
        name: vuevue
        ports:
        - containerPort: 80
