apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-simple-app
  labels:
    app: hpa-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-simple-app
  template:
    metadata:
      labels:
        app: hpa-simple-app
        tier: web
    spec:
      containers:
      - name: hpa-simple-app
        image: tiramisubliss/hpa-demo:2.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: hpa-simple-app
  labels:
    app: hpa-simple-app
spec:
  selector:
    app: hpa-simple-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer