apiVersion: v1
kind: Service
metadata:
  name: echocolor-green
spec:
  selector:
    app: example_code
    color: green
  ports:
  -
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort